#!/bin/sh
echo "INIT SCRIPT"
mkdir /proc
mkdir /sys
mkdir /tmp
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp
mount -t devtmpfs devtmpfs /dev
echo -e "\nThis boot took $(cut -d' ' -f1 /proc/uptime) seconds\n"
setsid  cttyhack /bin/sh
# exec /bin/sh

while true
do
    echo "Please press Crtl+a and x to quit —— $(date)"
    sleep 20
done